# Generated by Django 4.2 on 2023-05-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodblog',
            name='blog_title',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodblog',
            name='blogpost',
            field=models.TextField(),
        ),
    ]
